site_name: StaphSCAN
site_url: https://staphscan.readthedocs.io/
site_description: "StaphSCAN: a genome-based tool for Surveillance through Comprehensive Analysis and Normalized reporting of Staphylococcus aureus."
site_author: "Riccardo Bollini"
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: 
    - Overview: modules.md
    - Assembly: assembly.md
    - Typing: typing.md
    - Biofilm: biofilm.md                    
    - Resistance: resistance.md 
    - Virulence: virulence.md   
theme:
  name: readthedocs
  custom_dir: overrides

markdown_extensions:
  - admonition

  - codehilite



